rm(list=ls())
setwd("~")

###########################
# Eduardo Fierro Farah    # 
# Big Data project        #
# 5 / 4 /2017             #
# DAta Visualizations     #
###########################

require(stringr)
require(plyr)
require(ggplot2)
require(doBy)

################
# GENERAL NOTE #
################

# This code assumes that all the functions in the python code "dataForVisiualization.py"
# Have been succsesfully run on pyspark2. It takes as innput the un-merged folder 
# downloaded for the hadoop file system

###############
# Directories #
###############

# Directory on local machine where the outpur UNMERGED folders are placed:
dir <- "/Users/eduardofierro/Google Drive/SegundoSemestre/BigData/Project/Data/"

# Directory on local machine where you wish to output graphs generated by this code: 
dir_graphs <- "/Users/eduardofierro/Google Drive/SegundoSemestre/BigData/Project/Graphs/"

#############
# Functions #
#############

cleanerHadoop <- function(str_vector){
	str_vector <- as.character(str_vector)
	str_vector <- gsub("[(]", "", str_vector)
	str_vector <- gsub("[)]", "", str_vector)
	str_vector <- gsub("[']", "", str_vector)
	str_vector <- gsub("[,]", "", str_vector)
	return(as.numeric(str_vector))
}

cleanerHadoopSTR <- function(str_vector){
	str_vector <- as.character(str_vector)
	str_vector <- gsub("[(]", "", str_vector)
	str_vector <- gsub("[)]", "", str_vector)
	str_vector <- gsub("[']", "", str_vector)
	str_vector <- gsub("[,]", "", str_vector)
	return(str_vector)
}

##################
# Counts By year #
##################

files <- list.files(paste0(dir, "YearCounts.out/"))
files <- subset(files, files!="_SUCCESS" & files!="Icon\r") # Icon\r = Particular file if folder is in Google Drive. 
data.all <- data.frame()

for(x in 1:length(files)){
	data <- read.table(paste0(dir, "YearCounts.out/", files[x]))
	for(y in 1:ncol(data)){
		data[,y] <- cleanerHadoop(data[,y])
	}
    data.all <- rbind.fill(data, data.all)	
    rm(data)
}
rm(x, y, files)

names(data.all) <- c("year", "count")
graf1 <- ggplot(data= data.all, aes(x= year, y= count))  + 
         geom_line(na.rm=TRUE, colour= "#253494") + 
		 theme_bw() + 
		labs(x="Year", y="Total Crimes", title="Crimes by year \n All Data") + 
		theme(axis.title.x = element_text(face="bold", color="black", size=12),
		      axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(size=8, angle=90),
	    	     plot.title = element_text(face="bold", color = "black", size=16), legend.position=c(0, 1), legend.justification=c(0,1))
ggsave(paste(dir_graphs, "1_YearlyAll.png", sep="/"), plot= graf1)
# 655 NA's. 7 from 1015 (¿?)

# IT IS FROM 2006 That the data seems to be trustworthy. 
# Note: carefull with 2015. It's date of registry. 

rm(graf1)

data.all <- subset(data.all, data.all$year>=1900 & is.na(data.all$year)==F)
graf1 <- ggplot(data= data.all, aes(x= year, y= count))  + 
         geom_line(na.rm=TRUE, colour= "#253494") + 
		 theme_bw() + 
		labs(x="Year", y="Total Crimes", title="Crimes by year \n From 1900 onward") + 
		theme(axis.title.x = element_text(face="bold", color="black", size=12),
		      axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(size=8, angle=90),
	    	     plot.title = element_text(face="bold", color = "black", size=16), legend.position=c(0, 1), legend.justification=c(0,1))	  
ggsave(paste(dir_graphs, "2_YearlyFrom1900.png", sep="/"), plot= graf1)

rm(graf1)

data.all <- subset(data.all, data.all$year>=1900 & is.na(data.all$year)==F)
graf1 <- ggplot(data=data.all, aes(x= year, y= log(count)))  + 
         geom_line(na.rm=TRUE, colour= "#253494") + 
		 theme_bw() + 
		labs(x="Year", y="Natural Log of Total Crimes", title="Crimes by year (Log) \n From 1900 onward") + 
		theme(axis.title.x = element_text(face="bold", color="black", size=12),
		      axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(size=8, angle=90),
	    	     plot.title = element_text(face="bold", color = "black", size=16), legend.position=c(0, 1), legend.justification=c(0,1))	  
ggsave(paste(dir_graphs, "3_LogYearlyFrom1900.png", sep="/"), plot= graf1)
	    	      
# Question: From which year the data starts being reliable for intertemporal comparissons? 	
#           We think there is a inconsistency.... Crimes haven't increased, if anything, decreased.   

rm(graf1)

##################
# Counts By time #
##################

files <- list.files(paste0(dir, "HourMinutesCounts.out/"))
files <- subset(files, files!="_SUCCESS" & files!="Icon\r")
data.all <- data.frame()

for(x in 1:length(files)){
	data <- read.table(paste0(dir, "HourMinutesCounts.out/", files[x]))
	for(y in 1:ncol(data)){
		data[,y] <- cleanerHadoop(data[,y])
	}
    data.all <- rbind.fill(data, data.all)	
    rm(data)
}
rm(x, y)

rm(files)
names(data.all) <- c("hour", "minute", "drop", "count")
data.all$drop <- NULL

#### FIRST PROBLEM: THERE ARE OBSERVATIONS CODED 24, INSTEAD OF 0. 

data.all$hour[data.all$hour==24] <- 0
data.all <- summaryBy(count ~ hour + minute, data=data.all, FUN=sum, keep.names=T)

#### SECOND PROBLEM: 48 observations with NA

data.all <- subset(data.all, is.na(data.all$hour)==F)
data.all$seq <- seq(from=1, to=nrow(data.all))
data.all$labels <- paste(formatC(data.all$hour, width = 2, format = "d", flag = "0"),formatC(data.all$minute, width = 2, format = "d", flag = "0"), sep=":")
data.all$factor <- factor(data.all$seq, labels=data.all$labels)

data.all$completeHour <- "Any Other"
data.all$completeHour[data.all$minute==30] <- "Half-Hour (XX:30)"
data.all$completeHour[data.all$minute==0] <- "Exact Hour (XX:00)"


graf1 <- ggplot(data=data.all, aes(x= factor, y= count, color=completeHour))  + 
         geom_point(na.rm=TRUE) + 
         scale_color_manual(values = c("#41b6c4", "#2c7fb8", "#253494"), name="Minutes") +
         scale_x_discrete(breaks=c("00:00", "06:00", "12:00", "18:00", "23:59")) + 
		 theme_bw() + 
		 labs(x="Time", y="Count", title="Crimes by hour and minute \n All data frame") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		      axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(size=8, angle=45),
	    	      plot.title = element_text(face="bold", color = "black", size=16), legend.position=c(0, 1), legend.justification=c(0,1))	  
ggsave(paste(dir_graphs, "4_HourMinute.png", sep="/"), plot= graf1)

# As expected, they are rounded. I think that using even minutes is to risky, if we want to make 
# intertemporal comparisson, best thing is to use only our. (See frequency table for any time).

# Round by Hour
data.all <- summaryBy(count ~ hour, data=data.all, FUN=sum, keep.names=T)
data.all$seq <- seq(from=1, to=nrow(data.all))
data.all$labels <-formatC(data.all$hour, width = 2, format = "d", flag = "0")
data.all$factor <- factor(data.all$seq, labels=data.all$labels)
data.all$group <- 1

graf1 <- ggplot(data=data.all, aes(x= factor, y= count))  + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
         scale_x_discrete(breaks=c("00", "06", "12", "18", "23")) + 
		 theme_bw() + 
		 labs(x="Time", y="Count", title="Crimes by hour \n All data frame") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		      axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(size=8, angle=45),
	    	      plot.title = element_text(face="bold", color = "black", size=16), legend.position=c(0, 1), legend.justification=c(0,1))	  
ggsave(paste(dir_graphs, "5_Hour.png", sep="/"), plot= graf1)

# Better to work only with hours, leave minutes behind. 
# Possible problems????

rm(graf1, data.all)

######################
# General problem: I didn't find what "KY_CD = Three digit offense classification" is
# At first I thought KY_CD = OFNS_DESC "Description of offense corresponding with key code"
# BUT --> They DO NOT match 1:1; i.e. abortion. Possible mis-codification. 
# What to do? Take into consideration the str OFNS_DESC From now on. 
######################

#####################
# Offenses by types #
#####################

files <- list.files(paste0(dir, "OffensesCountsByYear.out/"))
files <- subset(files, files!="_SUCCESS" & files!="Icon\r")
data.all <- data.frame()

for(x in 1:length(files)){
	data <- read.table(paste0(dir, "OffensesCountsByYear.out/", files[x]), sep=",")
	for(y in 2:ncol(data)){
		# Changed to 2, because 1st is a string. CAREFULL 
		data[,y] <- cleanerHadoop(data[,y])
	}
	data[,1] <- cleanerHadoopSTR(data[,1])
    data.all <- rbind.fill(data, data.all)	
    rm(data)
}
rm(x, y)
rm(files)

# Do it from 2006 ownward, before, data seems a littlse "edgy". 

names(data.all) <- c("type", "year", "count")

data.all <- subset(data.all, data.all$year>=2006)
data.all <- subset(data.all, is.na(data.all$year)==F) # Also dropping NA in year

# From this year on, there are 18,775 with no type. Out of 5081794 (this is, 0.36% of the data)
# DROP EM' ALL!!!!
# They seem to be "evenly" distributed over time, so no need to wonder about self-selection
# temp <- subset(data.all, data.all$type=="")

# Some categories have only 1 observation. 
# IE. for 2015 "Fortune Telling". 

data.all <- subset(data.all, data.all$type!="")
all_cat <- summaryBy(count ~ type, data=data.all, FUN=sum, keep.names=T)
all_cat <- all_cat[order(all_cat$count, decreasing=T, na.last=T),] 
all_cat$total <- sum(all_cat$count)
all_cat$percent <- (all_cat$count / all_cat$total)
all_cat$seq <- seq(from=1, to=nrow(all_cat))
all_cat$factor <- factor(all_cat$seq, labels=all_cat$type)
all_cat$group <- 1

graf1 <- ggplot(data= all_cat, aes(x= factor, y= count)) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 labs(x="Crime Category", y="Count", title="Crimes by Category \n 2006 onwards") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), axis.text.x= element_text(hjust = 1,vjust = 1, size=4, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16))	  
ggsave(paste(dir_graphs, "6_Type.png", sep="/"), plot= graf1)

main_cat <- all_cat$type[1:6]
rm(graf1, all_cat)

###########################################
# Evolution in time of principal offenses #
###########################################

data_prin <- subset(data.all, data.all$type %in% main_cat)
data_prin <- data_prin[order(data_prin$type, data_prin$year),] 
data_prin$group <- 1
data_prin$year_Str <- as.character(data_prin$year)

graf1 <- ggplot(data= data_prin, aes(x= year_Str, y= count)) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 facet_wrap(~type) + 
		 labs(x="Year", y="Count", title="Evolution on crime for main categories") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), 
		       axis.text.x= element_text(hjust = 1,vjust = 1, size=8, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16), 
	    	   strip.text = element_text(size= 8))	  
ggsave(paste(dir_graphs, "7_MainCatsOverTime.png", sep="/"), plot= graf1)
rm(graf1, data_prin, main_cat)


#################################################
# Differences by year of occurence and reported #
#################################################

files <- list.files(paste0(dir, "YearDifferences.out/"))
files <- subset(files, files!="_SUCCESS" & files!="Icon\r")
data.all <- data.frame()

for(x in 1:length(files)){
	data <- read.table(paste0(dir, "YearDifferences.out/", files[x]), sep=",")
	for(y in 2:ncol(data)){
		# Changed to 2, because 1st is a string. CAREFULL 
		data[,y] <- cleanerHadoop(data[,y])
	}
	data[,1] <- cleanerHadoopSTR(data[,1])
    data.all <- rbind.fill(data, data.all)	
    rm(data)
}
rm(x, y)
rm(files)

names(data.all) <- c("occurence", "reported", "count")

# Drop NA's
data.all <- subset(data.all, is.na(data.all$occurence)==F & is.na(data.all$reported)==F)

# keep only years above 1900 (credible years)
data.all <- subset(data.all, data.all$occurence > 1900)
data.all$occurence <- as.numeric(data.all$occurence )
data.all$dif <- data.all$reported - data.all$occurence

collapsed <- summaryBy(count ~ dif, FUN=sum, keep.names=T,data=data.all)
collapsed$group <- 1

graf1 <- ggplot(data= collapsed, aes(x= dif, y= count)) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 labs(x="Difference in years", y="# of cases", title="Years between occurence and reported") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), 
		       axis.text.x= element_text(hjust = 1,vjust = 1, size=8, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16)) 
ggsave(paste(dir_graphs, "8_DiffYears.png", sep="/"), plot= graf1)
rm(graf1)

graf1 <- ggplot(data= collapsed, aes(x= dif, y= log(count))) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 labs(x="Difference in years", y="Log of # of cases", title="Years between occurence and reported") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), 
		       axis.text.x= element_text(hjust = 1,vjust = 1, size=8, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16)) 
ggsave(paste(dir_graphs, "9_LogDiffYears.png", sep="/"), plot= graf1)
rm(graf1, collapsed, data.all)

# keep only years above 2006 (even more credible years)
data.all <- subset(data.all, data.all$occurence >= 2006)
data.all$occurence <- as.numeric(data.all$occurence )
data.all$dif <- data.all$reported - data.all$occurence

collapsed <- summaryBy(count ~ dif, FUN=sum, keep.names=T,data=data.all)
collapsed$group <- 1

graf1 <- ggplot(data= collapsed, aes(x= dif, y= count)) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 labs(x="Difference in years", y="# of cases", title="Years between occurence and reported  \n Occurence in 2006 ownwards") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), 
		       axis.text.x= element_text(hjust = 1,vjust = 1, size=8, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16)) 
ggsave(paste(dir_graphs, "10_DiffYears_2006.png", sep="/"), plot= graf1)
rm(graf1)

graf1 <- ggplot(data= collapsed, aes(x= dif, y= log(count))) + 
         geom_point(na.rm=TRUE, color="#253494") + 
         geom_line(color="#253494", aes(group=group)) + 
		 theme_bw() + 
		 labs(x="Difference in years", y="Log of # of cases", title="Years between occurence and reported  \n Occurence in 2006 ownwards") + 
		 theme(axis.title.x = element_text(face="bold", color="black", size=12),
		       axis.title.y = element_text(face="bold", color="black", size=12), 
		       axis.text.x= element_text(hjust = 1,vjust = 1, size=8, angle=45),
	    	   plot.title = element_text(face="bold", color = "black", size=16)) 
ggsave(paste(dir_graphs, "11_LogDiffYears_2006.png", sep="/"), plot= graf1)
rm(graf1)